Name: Plugin Build

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version (x.x.x)'
        required: true
        default: 'continuous'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter & Caching
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.2
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter"

      - name: Cache Dart pub global
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install hetu_script_dev_tools
        run: dart pub global activate hetu_script_dev_tools

      - name: Run build & archive
        run: |
          make
          make archive
        shell: bash
      
      - name: Upload plugin archive
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact
          path: build/plugin.smplug
          retention-days: 3

      - name: Upload to release (${{ github.event.inputs.version }})
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: build/plugin.smplug
